cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_LOG_sim/FP_LOG_memoryC0_uid134_lnTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_LOG_sim/FP_LOG_memoryC0_uid135_lnTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_LOG_sim/FP_LOG_memoryC1_uid138_lnTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_LOG_sim/FP_LOG_memoryC2_uid142_lnTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_DIVIDE_sim/FP_DIVIDE_memoryC0_uid146_invTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_DIVIDE_sim/FP_DIVIDE_memoryC0_uid147_invTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_DIVIDE_sim/FP_DIVIDE_memoryC1_uid150_invTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_DIVIDE_sim/FP_DIVIDE_memoryC1_uid151_invTables_lutmem.hex ./
cp -f C:/Users/luke/OneDrive/FYP/QUARTUS/de1_soc_GHRD/FP_DIVIDE_sim/FP_DIVIDE_memoryC2_uid154_invTables_lutmem.hex ./
